# Generated by Django 4.2.15 on 2024-08-12 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grades', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student'),
        ),
        migrations.AddField(
            model_name='courseinscription',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grades.course'),
        ),
        migrations.AddField(
            model_name='courseinscription',
            name='inscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grades.inscription'),
        ),
        migrations.AddField(
            model_name='course',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.professor'),
        ),
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grades.subject'),
        ),
        migrations.AddConstraint(
            model_name='restriction',
            constraint=models.UniqueConstraint(fields=('subject', 'restriction'), name='unique_subject_restriction'),
        ),
        migrations.AddConstraint(
            model_name='inscription',
            constraint=models.UniqueConstraint(fields=('student', 'date'), name='unique_student_date'),
        ),
        migrations.AddConstraint(
            model_name='courseinscription',
            constraint=models.UniqueConstraint(fields=('inscription', 'course'), name='unique_inscription_course'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('subject', 'professor'), name='unique_subject_professor'),
        ),
    ]
